INSERT INTO Artists VALUES('Ghost')
INSERT INTO Artists VALUES('System of a down')
INSERT INTO Artists VALUES('Avenged Sevenfold')
INSERT INTO Artists VALUES('Coldplay')
INSERT INTO Artists VALUES('Ariana Grande')

INSERT INTO RecordLabels VALUES('Rise Above')
INSERT INTO RecordLabels VALUES('Loma Vista')
INSERT INTO RecordLabels VALUES('Republic')
INSERT INTO RecordLabels VALUES('Parlophone')
INSERT INTO RecordLabels VALUES('American Recordings')
INSERT INTO RecordLabels VALUES('Capitol')
INSERT INTO RecordLabels VALUES('Warner Bros')
INSERT INTO RecordLabels VALUES('Hopeless')
INSERT INTO RecordLabels VALUES('Good Life')

-- Ghost
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Opus Eponymous', 1, 1, 1)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Infestissumam', 2, 1, 2)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Meliora', 3, 1, 2)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Prequelle', 1, 1, 2)

-- System of a down
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('System of a Down', 2, 2, 5)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Toxicity', 2, 2, 5)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Steal This Album!', 3, 2, 5)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Mezmerize', 3, 2, 5)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Hypnotize', 3, 2, 5)

-- Avenged Sevenfold
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Sounding the Seventh Trumpet', 3, 3, 9)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Waking the Fallen', 3, 3, 8)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('City of Evil', 3, 3, 7)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Avenged Sevenfold', 3, 3, 7)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Nightmare', 3, 3, 7)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Hail to the King', 3, 3, 7)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('The Stage', 3, 3, 6)

-- Coldplay
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Parachutes', 3, 4, 4)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('A Rush of Blood to the Head', 3, 4, 4)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('X&Y', 3, 4, 4)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Viva la Vida or Death and All His Friends', 3, 4, 4)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Mylo Xyloto', 3, 4, 4)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Ghost Stories', 3, 4, 4)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('A Head Full of Dreams', 4, 1, 4)

-- Ariana Grande
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Yours Truly', 3, 5, 3)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('My Everything', 3, 5, 3)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Dangerous Woman', 3, 5, 3)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Sweetener', 3, 5, 3)
INSERT INTO Albums (Name, AlbumType, ArtistId, RecordLabelId) VALUES('Thank U, Next', 3, 5, 3)

INSERT INTO Inventory VALUES (1, 24)
INSERT INTO Inventory VALUES (2, 254)
INSERT INTO Inventory VALUES (3, 75)
INSERT INTO Inventory VALUES (4, 757)
INSERT INTO Inventory VALUES (5, 575)
INSERT INTO Inventory VALUES (6, 454)
INSERT INTO Inventory VALUES (7, 4)
INSERT INTO Inventory VALUES (8, 7)
INSERT INTO Inventory VALUES (9, 77)
INSERT INTO Inventory VALUES (10, 97)
INSERT INTO Inventory VALUES (11, 577)
INSERT INTO Inventory VALUES (12, 4444)
INSERT INTO Inventory VALUES (13, 789)
INSERT INTO Inventory VALUES (14, 699)
INSERT INTO Inventory VALUES (15, 69)
INSERT INTO Inventory VALUES (16, 694)
INSERT INTO Inventory VALUES (17, 54)
INSERT INTO Inventory VALUES (18, 45)
INSERT INTO Inventory VALUES (19, 111)
INSERT INTO Inventory VALUES (20, 9)
INSERT INTO Inventory VALUES (21, 54)
INSERT INTO Inventory VALUES (22, 6)
INSERT INTO Inventory VALUES (23, 50)
INSERT INTO Inventory VALUES (24, 11)
INSERT INTO Inventory VALUES (25, 545)
INSERT INTO Inventory VALUES (26, 77)
INSERT INTO Inventory VALUES (27, 7777)
INSERT INTO Inventory VALUES (28, 444)
